channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - biopython
  - jax
  - imageio
  - tqdm
  - ipykernel
  - ipywidgets
  - pytest
